--2주차 과제

--(Q1)
/*
1. SELECT 2. FROM 3. 별칭
*/

--(Q2)
SELECT DISTINCT JOB
  FROM EMP;


--(Q3)
  SELECT EMPNO AS "EMPLOYEE_NO",ENAME AS "EMPLOYEE_NAME", JOB, MGR AS "MANAGER", 
         HIREDATE, SAL AS "SALARY", COMM AS "COMMITION", DEPTNO AS "DEPARTMENT_NO"
    FROM EMP
ORDER BY DEPTNO DESC, ENAME ASC;

