--3주차 과제

--Q1
SELECT *
  FROM EMP
 WHERE ENAME LIKE '%S';
 
 
 
--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
 
 
 
--Q3
--집합 X
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE SAL > 2000
   AND DEPTNO IN (20, 30);
--집합O
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE SAL > 2000
INTERSECT
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO IN (20, 30);
 
 
--Q4
SELECT *
  FROM EMP
 WHERE SAL <= 2000 OR SAL >= 3000; 
 

--Q5
SELECT ENAME, DEPTNO, SAL, DEPTNO
  FROM EMP
 WHERE SAL NOT BETWEEN 1000 AND 2000
   AND ENAME LIKE '%E%'
   AND DEPTNO = 30;
   

--Q6
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND JOB IN ('MANAGER', 'CLERK')
   AND ENAME NOT LIKE '_L%';
   
--Q6-2
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND (JOB = 'MANAGER' OR JOB = 'CLERK')
   AND ENAME NOT LIKE '_L%';